server:
  port: 8031
spring:
  application:
    name: microservice-hystrix-turbine
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:111111@localhost:8761/eureka
  instance:
    prefer-ip-address: true
turbine:
  aggregator:
    clusterConfig: default
  appConfig: microservice-service-consumer-ribbon-hystrix,microservice-service-consumer-feign-hystrix
  clusterNameExpression: "'default'"
# turbine:
#  aggregator:
#    clusterConfig: MICROSERVICE-SERVICE-CONSUMER-RIBBON-HYSTRIX
#  appConfig: microservice-service-consumer-ribbon-hystrix
# 