security:
  basic:
    enabled: true
  user:
    name: user
    password: 111111
server:
  port: 8761
eureka:
  instance:
    statusPageUrlPath: ${management.context-path}/info
    healthCheckUrlPath: ${management.context-path}/health
  client:
    healthcheck:
      enabled: true
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://user:111111@localhost:8761/eureka