spring:
  application:
    name: microservice-service-consumer-ribbon
server:
  port: 7901
 
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:111111@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    